# MD013/line-length: Line length, https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md013.md
MD013:
  line_length: 99999

# MD024/no-duplicate-heading: Multiple headings with the same content, https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md024.md
MD024:
  siblings_only: true

# MD026/no-trailing-punctuation: Trailing punctuation in heading, https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md026.md
MD026:
  punctuation: ".,;:"

# MD08/no-blanks-blockquote: Blank line inside blockquote, https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md028.md
MD028: false

# MD049/emphasis-style: Emphasis style, https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md049.md
MD049:
  style: consistent

# MD059/descriptive-link-text Link text should be descriptive, https://github.com/DavidAnson/markdownlint/blob/main/doc/md059.md
MD059: false