apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: marketplace-tools
  annotations:
    autogenSpecType: SINGLE_VM
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Google Cloud Marketplace Terraform Module
    version: 1.0.401
    actuationTool:
      flavor: Terraform
      version: ">= 1.2"
    description: {}
    softwareGroups:
      - type: SG_OS
        software:
          - title: debian
            version: "12"
      - software:
          - title: norsk-studio
            version: "1.0.401"
          - title: norsk
            version: "1.0.401"
          - title: nginx
            version: "1.27.4"
          - title: oauth2-proxy
            version: "7.8.2"
          - title: coturn
            version: "4.6.3"
  content: {}
  interfaces:
    variables:
      - name: project_id
        description: The ID of the project in which to provision resources.
        varType: string
        required: true
      - name: goog_cm_deployment_name
        description: The name of the deployment and VM instance.
        varType: string
        required: true
      - name: source_image
        description: The image name for the disk for the VM instance.
        varType: string
        defaultValue: projects/id3as-public/global/images/norsk-studio-byol-debian-12-x86-64-2025-05-13
      - name: zone
        description: The zone for the solution to be deployed.
        varType: string
        defaultValue: us-central1-a
      - name: boot_disk_type
        description: The boot disk type for the VM instance.
        varType: string
        defaultValue: pd-balanced
      - name: boot_disk_size
        description: The boot disk size for the VM instance in GBs
        varType: integer
        defaultValue: 25
      - name: machine_type
        description: The machine type to create, e.g. e2-small
        varType: string
        defaultValue: e2-standard-8
      - name: accelerator_type
        description: The accelerator type resource exposed to this instance. E.g. nvidia-tesla-p100.
        varType: string
        defaultValue: nvidia-tesla-p100
      - name: accelerator_count
        description: The number of the guest accelerator cards exposed to this instance.
        varType: integer
        defaultValue: 0
      - name: networks
        description: The network name to attach the VM instance.
        varType: list(string)
        defaultValue:
          - default
      - name: sub_networks
        description: The sub network name to attach the VM instance.
        varType: list(string)
        defaultValue: []
      - name: external_ips
        description: The external IPs assigned to the VM for public access.
        varType: list(string)
        defaultValue:
          - EPHEMERAL
      - name: enable_tcp_80
        description: Allow HTTP traffic from the Internet (optional, redirects to HTTPS)
        varType: bool
        defaultValue: true
      - name: tcp_80_source_ranges
        description: Source IP ranges for HTTP traffic
        varType: string
        defaultValue: ""
      - name: enable_tcp_443
        description: Allow HTTPS traffic from the Internet
        varType: bool
        defaultValue: true
      - name: tcp_443_source_ranges
        description: Source IP ranges for HTTPS traffic
        varType: string
        defaultValue: ""
      - name: enable_tcp_3478
        description: Allow TCP port 3478 (STUN/TURN) traffic from the Internet
        varType: bool
        defaultValue: true
      - name: tcp_3478_source_ranges
        description: Source IP ranges for TCP port 3478 traffic
        varType: string
        defaultValue: ""
      - name: enable_udp_3478
        description: Allow UDP port 3478 (STUN/TURN) traffic from the Internet
        varType: bool
        defaultValue: true
      - name: udp_3478_source_ranges
        description: Source IP ranges for UDP port 3478 traffic
        varType: string
        defaultValue: ""
      - name: enable_udp_5001
        description: Allow UDP port 5001 traffic (example SRT port) from the Internet
        varType: bool
        defaultValue: true
      - name: udp_5001_source_ranges
        description: Source IP ranges for UDP port 5001 traffic
        varType: string
        defaultValue: ""
      - name: ip_forward
        description: Whether to allow sending and receiving of packets with non-matching source or destination IPs.
        varType: bool
        defaultValue: false
      - name: domain_name
        description: The domain name that you will access this Norsk Studio deployment through, which you must set up through your DNS provider to point to the VM instance.
        varType: string
      - name: certbot_email
        description: The email where you will receive HTTPS certificate expiration notices from Let's Encrypt.
        varType: string
      - name: enable_cloud_logging
        description: Enables Cloud Logging.
        varType: bool
        defaultValue: true
      - name: enable_cloud_monitoring
        description: Enables Cloud Monitoring.
        varType: bool
        defaultValue: true
    outputs:
      - name: instance_machine_type
        description: Machine type for the compute instance.
      - name: instance_nat_ip
        description: External IP of the compute instance.
      - name: instance_network
        description: Self-link for the network of the compute instance.
      - name: instance_self_link
        description: Self-link for the compute instance.
      - name: instance_zone
        description: Zone for the compute instance.
      - name: site_url
        description: Site Url
      - name: admin_user
        description: Username for Admin password.
      - name: admin_password
        description: Password for Admin.
