# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "github-pages", "= 231"

gem "ffi", "< 1.17.0"

gem "jekyll-include-cache", "= 0.2.1"
gem "jekyll-octicons", "~> 14.2"

gem "minimal-mistakes-jekyll"
