name: Create a new gHack

on:
  workflow_dispatch:
    inputs:
      hackId:
        description: The id of the hack, this is used as folder name, short, sweet and all lower/snake case, e.g. mlops-on-gcp
        required: true
      hackTitle:
        description: The title of the hack, mainly used as lab title for Qwiklabs, e.g IoT hack of the Century
        required: true
      hackAuthor:
        description: The email address of the author, used in QL_OWNER, you can add more later, e.g. user@example.com
        required: true
jobs:
  scaffold:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.event.inputs.hackId }}
      HACK: ${{ github.event.inputs.hackId }}
      AUTHOR: ${{ github.event.inputs.hackAuthor }}
      TITLE: ${{ github.event.inputs.hackTitle }}
    steps:
      - uses: actions/checkout@v4
      - name: Create new branch
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "${{ env.AUTHOR }}"
          git checkout -b ${{ env.BRANCH_NAME }}
      - name: Generate the required structure
        run: tools/setup-newhack.sh -h "${{ env.HACK }}" -t "${{ env.TITLE }}" -a "${{ env.AUTHOR }}"
      - name: Push branch
        run: |
          git add .
          git commit -m "Inital commit for the hack ${{ env.HACK }}"
          git push -u origin ${{ env.BRANCH_NAME }}